# docker-compose para montar 
# Banco de Dados: Postgres
# Nginx para servidor proxy HTTP e reverso
# Imagem para aplicação Python 
# Imagem para mensageria queue
# Duvidas: @fa_bioaraujo <fabioaraujp@mail.com>
# https://fabioaraujo.info

version: '3'
volumes:
  dados:
networks: 
  banco:
  web:
  fila:      
services:
  db:
    image: postgres:9.6
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scrpts
      - ./scripts:/scripts
      # convenção... leia na documentaçao do Docker, procure : entrypoint-initdb
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco  
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80   
    networks:
      - web    
    depends_on:
      - app 
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh 
    networks:
      - banco    
      - web
      - fila
    depends_on:
      - db  
      - queue
    environment:
      - DB_NAME=aquiTaQualquerCoisa-vaiSerSubstituidoPor-peloaquivo-docker-compose-override
  queue:
    image: redis:3.2
    networks:
      - fila
  worker:
    build: worker
    volumes:
      # Workes
      - ./worker:/worker
    working_dir: /worker
    command: worker.py
    networks:
      - fila
    depends_on: 
      - queue



